# Generated by Django 2.2.11 on 2020-05-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='upvoted',
            new_name='post_upvoted',
        ),
    ]
