# Generated by Django 2.2.11 on 2020-05-29 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0002_auto_20200529_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_upvoted',
        ),
        migrations.RemoveField(
            model_name='post',
            name='total_upvotes',
        ),
        migrations.CreateModel(
            name='PostUser_Upvotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upvotes', to='feed.Post')),
                ('upvoted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upvotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
